export const ACTION = {
    LOGIN_USER: "LOGIN_USER",
    SAVE_PLACES: "SAVE_PLACES",
    SAVE_FROM_PLACE: "SAVE_FROM_PLACE",
    REMOVE_FROM_PLACE: "REMOVE_FROM_PLACE",
    SAVE_TO_PLACES: "SAVE_TO_PLACES",
    REMOVE_TO_PLACES: "REMOVE_TO_PLACES",
}